### ISSUE TITLE
Add documentation - limitation on AlchemyAPI (OpenWhisk docs).

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/BluePic#222]
Add details to the OpenWhisk documentation on the limitation that exists regarding the alchemy api service. We discovered that only one instance of the service per account can have credentials bound to it. This means that if a developer already has an instance of this service with credentials and then tries to provision bluepic, it will fail.

**Comment by triceam** [comment]
Added the following to the OpenWhisk.md docs under the `Alchemy` secion:

> _*Note:* If you receive the following error message when creating your Alchemy service instance: Only one free key is allowed per account in a 24-hour period., then be sure to check if you already have an Alchemy service created for your Bluemix account. Only one Alchemy service instance is allowed per Bluemix user Id. You can reuse your Alchemy key from an exsiting app without having to create a new Alchemy instance. This error message is misleading because you will not be able to create a new Alchemy instance in 24 hours._
