### ISSUE TITLE
Use BFG to remove any old credentials data.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/BluePic#256]
https://help.github.com/articles/remove-sensitive-data/

**Comment by xanderbuck** [comment]
Cleaned all branches of sensitive files and deleted any unnecessary branches.

Also updated the wiki with how to use the BFG Repo Cleaner tool:
https://github.com/IBM-Swift/BluePic/wiki/Using-BFG-Repo-Cleaner-tool-to-remove-sensitive-files-from-your-git-repo
