### ISSUE TITLE
If image caption is too long, there is no way to read it in the app, once the image is posted.

### ISSUE THREAD

**Issue by tfrank64** [IBM-Swift/BluePic#265]

**Comment by king33** [comment]
Need to get feedback from design on the best way to handle this.

**Comment by king33** [comment]
![img_5995](https://cloud.githubusercontent.com/assets/14813248/18916626/a7985160-855a-11e6-887c-9f1e3327ec7f.PNG)
Jake Cummings from designs says:
" Instagram at the end of a caption adds a " ... more " in grey and truncates the caption, tapping it expands to see the rest.
Bottom right of the screen I sent shows how they handle it."

**Comment by tfrank64** [comment]
Image detail now looks like this for long text:
![simulator screen shot oct 20 2016 9 44 18 am](https://cloud.githubusercontent.com/assets/4023136/19564629/d134a342-96a9-11e6-8aaa-d76d5ff1bb54.png)
