### ISSUE TITLE
Cocoapods 1.0 support?

### ISSUE THREAD

**Issue by csantanapr** [IBM-Swift/BluePic#272]
I have pod 1.0.0, is this supported?

I see in https://github.com/IBM-Swift/BluePic/blob/master/BluePic-iOS/Podfile.lock#L48
COCOAPODS: 0.39.0

Having some issue running `pod install` the xcworkspace looses the Pods project.

Here is my env (pod 1.0, swift 05-03-a)
```
$ pod --version
1.0.0
~/dev/swift/cs-bluepic (master)
👽  $ swift --version
Apple Swift version 3.0-dev (LLVM dffa09ffd8, Clang 1e6cba3ce3, Swift d2aee43220)
Target: x86_64-apple-macosx10.9
```

**Comment by rolivieri** [comment]
@csantanapr There is no need to run `pod install`. When you clone the repo, everything is set and ready to go.

**Comment by csantanapr** [comment]
I'm trying to add a feature to the app and need to add a new pod

**Comment by tfrank64** [comment]
@csantanapr so the answer is no, we have not tested Cocoapods support with version 1.0. Version 0.39.0 is what we know works. That said, running `pod install` with 0.39.0 still gives an issue with the BMSCore dependency. There is a workaround [here](https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-swift-security-facebookauthentication/issues/3) which involves commenting out some `.modulemap` file values. We are hoping this is fixed soon.

**Comment by csantanapr** [comment]
Could you put this info in the README? for the user to use 0.39.0 and how to workaround temporarily ?

**Comment by tfrank64** [comment]
I don't think it is necessary to have in the Readme since we are not requiring the developer to use cocoapods or run `pod install`. Adding extra pods is completely optional, so we would prefer not to lengthen the Readme anymore. In the future, we expect pods to work just fine without a workaround, if the developer desired to add more pods.

**Comment by csantanapr** [comment]
Sounds good, I close the issue
