### ISSUE TITLE
Build Errors running iOS App RNCryptor.swift

### ISSUE THREAD

**Issue by csantanapr** [IBM-Swift/BluePic#273]
DOA error about RNCryptor.swift

Steps to reproduce (As of 06/18/16)
1. Download IBM Cloud Tools for Swift (1.0.1.5 (30) )
2. Click new project "foo-bluepic"
3. Select Bluemix app name "foo-bluepic"
4. Wait for Cloud Runtime to be green (Running)
5. Click Reveal in Finder "BluePix.xcworkspace" (Didn't click open as I have XCode 8 and also had problem with XCode 8)
6. Right click on "BluePix.xcworkspace" Select XCode 7.3.1
7. If not already set Toolchain to the one specified in [BluePic README](https://github.com/IBM-Swift/BluePic/blob/master/README.md) (XCode  -> ToolsChains -> swift-DEVELOPMENT-SNAPSHOT-2016-05-03-a)
8. Clean XCode workspace CMD+SHIFT+K
9.  Click Run on iPhone 6s Simulatulator
10. Build Error for RNCryptor.swift

Multiple Errors
![image](https://cloud.githubusercontent.com/assets/1094878/16170674/93cec99c-3529-11e6-9e59-a8f9cd9e009b.png)

**Comment by rolivieri** [comment]
@csantanapr The BluePic iOS app code was tested and developed using Xcode 7.3 (default toolchain). For the back-end components, a different toolchain was used: DEVELOPMENT-SNAPSHOT-2016-05-03-a version (see the Swift version section in the README). Attempting to compile the iOS app code with the DEVELOPMENT-SNAPSHOT-2016-05-03-a version of the Swift binaries won't work.

**Comment by rolivieri** [comment]
@csantanapr We are closing this issue since compiling the iOS app code with the `DEVELOPMENT-SNAPSHOT-2016-05-03-a` version of the Swift binaries is not supported. If you have any other questions, let us know.

**Comment by csantanapr** [comment]
np
