### ISSUE TITLE
BluePic iOS white screen on first run

### ISSUE THREAD

**Issue by csantanapr** [IBM-Swift/BluePic#274]
I was able to workaround #273  by setting XCode 7.3.1 to Default ToolChain

This is the first time I'm building and running the App

Steps to reproduce:
1. Right click BluePic.xcworkspace open with -> XCode 7.3.1 
2. Set XCode->ToolChains -> Default ToolChain
3. Clean CMD+SHIFT+K
4. Build CMD+B
5. Run IPhone 6s Simulator
6. Tap Yes to Popup -> App Runs and Displays Alert "Allow Notifications?" 
7. Tap sign-in later

Verified Bluepic Cloud Runtime is running (green)

App shows white screen, no photos and XCode debug area with message "user needs to log into Facebook, showing login"

![image](https://cloud.githubusercontent.com/assets/1094878/16170750/8a775bd2-352b-11e6-8b9f-34af234a1e45.png)

![image](https://cloud.githubusercontent.com/assets/1094878/16170756/c305cd4e-352b-11e6-9528-f16c4007e707.png)

**Comment by tfrank64** [comment]
@csantanapr I am not able to reproduce this issue using the steps you mentioned. I did notice this issue last week, so I created a fix for it that is now in the master branch. Please make sure you have the latest from master because what should happen is that you see the eye spinning at the top and then slowly the view is filled out with image data.

As far as that "login to Facebook" message, you should only **need** to login if you have MCA configured, I will update that message to say so. thanks.

**Comment by csantanapr** [comment]
Can you provide the commit hash to the fix?
I'm using the IBM Cloud Tool to create the project, is the tool pulling the master branch?

**Comment by tfrank64** [comment]
Sure, this commit 1de505f2db4e8e60681bbf6a8e1122cd86334944
And yes, the tool is pulling from the master branch of BluePic.

**Comment by rolivieri** [comment]
@csantanapr Are you still having this issue after the change Taylor committed yesterday?

**Comment by csantanapr** [comment]
@tfrank64 @rolivieri 

I'm still having trouble using latest from master.

```
$ git clone https://github.com/IBM-Swift/BluePic.git
$ git log
commit ab8d1bb59d46f05504ebfe5f81ee1edc32d6302d
Author: rolivieri <roliv@us.ibm.com>
Date:   Mon Jun 20 14:08:42 2016 -0500

    More updates README.
$ open BluePic-iOS/BluePic.xcworkspace
```
Reset simulator.
Edit bluemix.plist with correct values
Run the App

![image](https://cloud.githubusercontent.com/assets/1094878/16242578/00d7d26a-37c1-11e6-8961-970acbb207bb.png)

**Comment by rolivieri** [comment]
@csantanapr Which method are you using from the README file? Method 1 or method 2?

**Comment by csantanapr** [comment]
Method 2
Not using the IBM Cloud Tool 
Just git clone a fresh copy and open XCode

**Comment by rolivieri** [comment]
@csantanapr Got it. In that case, did you execute steps 1-7 under Method 2 before attempting to run the app?

**Comment by csantanapr** [comment]
@rolivieri I think it was user error, I didn't switched isLocal to NO

![image](https://cloud.githubusercontent.com/assets/1094878/16252139/b4dabfe2-37f9-11e6-8071-aef0cd373525.png)

I switched and the problem is now solved.

Thanks for being patient with me thanks a lot for all the help guys 👍
