### ISSUE TITLE
Build Error for BluePic-Server - No such module CouchDB

### ISSUE THREAD

**Issue by csantanapr** [IBM-Swift/BluePic#277]
My env:
In terminal setup:
swift-DEVELOPMENT-SNAPSHOT-2016-05-03-a
$ swift --version
Apple Swift version 3.0-dev (LLVM dffa09ffd8, Clang 1e6cba3ce3, Swift d2aee43220)
Target: x86_64-apple-macosx10.9
XCode 8 beta setup to default ToolChain 

Steps to reproduce:
1. Create a new BluePic project using IBM Cloud Tools for Swift
2. Open BluePic-Server in terminal
3. Run `swift build` (finished with no errors)
4. Run `swift build -X` (generated ./BluePic-Server.xcodeproj)
5. Open in XCode 8 Run `open -a /Applications/Xcode-beta.app BluePic-Server.xcodeproj`

Results:
Build Error No such module CouchDB
![image](https://cloud.githubusercontent.com/assets/1094878/16171186/87ac4178-3536-11e6-928d-bd15a6cf7329.png)

I see CouchDB listed, then why the error
![image](https://cloud.githubusercontent.com/assets/1094878/16171208/1f3d76f6-3537-11e6-9e69-2de77c476037.png)

Switched to server->My Mac and try to Build more errors:
![image](https://cloud.githubusercontent.com/assets/1094878/16171220/8f7e61e6-3537-11e6-94b0-1fb7e44b36ec.png)

**Comment by rolivieri** [comment]
@csantanapr Hello, since you are using The IBM Cloud Tools for project generation, I’d recommend using their feedback(http://ibm.biz/Bd4QPP) page to provide feedback and/or report any issues you may be running into. Having said that, I noticed you are using Xcode 8. The BluePic iOS app code was tested and developed using `Xcode 7.3` (default toolchain). For the back-end components, a different toolchain was used: DEVELOPMENT-SNAPSHOT-2016-05-03-a version (see the `Swift version` section in the README).

**Comment by csantanapr** [comment]
To use XCode 8 for the server project do I need to set the tool chain to 5/3 ?
Xcode 8 comes wit tool gain 6/13 I think

**Comment by csantanapr** [comment]
I reported all issues using their form but pointed here to github since it's easier to attached terminal output and screenshots

**Comment by tfrank64** [comment]
We did our development with Xcode 7.3.1, but yes if you can find a way to use the 5/3 toolchain in Xcode 8, then it should work for the Server project. I noticed many of my old toolchains are incompatible with Xcode 8.

**Comment by csantanapr** [comment]
Do you mind updating the README to help others trying to setup this locally. About using XCode 7 and to use a different tool chain for iOS project and a different one for server?

**Comment by tfrank64** [comment]
Ricardo updated the Readme this morning with your second point, but we could probably make it more clear that Xcode 8 may not work. Were you able to run the server in Xcode 8?

**Comment by tfrank64** [comment]
@csantanapr We made another update to the Readme so it is more clear. I will close this issue unless there is something else?

**Comment by csantanapr** [comment]
The update help now.
In addition can you add something about the backend component that user needs to use XCode 7 and build 05/03?

The back-end components (i.e. Kitura-based server and OpenWhisk actions) of the BluePic app work with the DEVELOPMENT-SNAPSHOT-2016-05-03-a version of the Swift binaries. **To run the back-end with Xcode, use Xcode 7.3.1 and configure it to use the specified ToolChain. At the moment, any other versions of Xcode are not guaranteed to work.**

**Comment by rolivieri** [comment]
@csantanapr Using Xcode for the back-end code is completely optional. Having said that, we just added one more paragraph to state that it is possible.

**Comment by csantanapr** [comment]
Yep I understand it's optional, but I happened to have a Mac and like Xcode so why not use it

README looks OK now I will close now
