### ISSUE TITLE
Source of Kitura callback info

### ISSUE THREAD

**Issue by iainhouston** [IBM-Swift/BluePic#280]
It's not clear where to find the Kitura server callback info when configuring `local.env` as, unlike the the other "credentials" this info is not found in the *Connections* tab of the app.

I assume I am right in thinking that the `KITURA_host`, `KITURA_port`, and `KITURA_schema` can each be deduced from the URL of the page you get from clicking *View app* button on the app's page of the (new) Bluemix console.

**Comment by triceam** [comment]
Thanks, this is referring to where  the kitura server is running. This is the route of the CloudFoundry application if you're running on Bluemix.  You can see details in the "Service Credentials" section under this readme (last paragraph in that section): https://github.com/IBM-Swift/BluePic/blob/master/Docs/OpenWhisk.md

**Comment by rolivieri** [comment]
@iainhouston We made a few minor updates to the docs, hoping that would make things a little clearer. Yes, you are correct, those values can be deduces from the URL. Updated docs: https://github.com/IBM-Swift/BluePic/blob/master/Docs/OpenWhisk.md

**Comment by iainhouston** [comment]
Thanks @rolivieri that's clear now
