### ISSUE TITLE
Missing documentation for "Configuring a Notification Service"

### ISSUE THREAD

**Issue by iainhouston** [IBM-Swift/BluePic#282]
In the section in this repo's README describing *Configuring a Notification Service* the [target link](https://new-console.ng.bluemix.net/docs/services/mobilepush/c_ios_enable.html#enable-push-ios-notifications-install) in the BlueMix documentation has no content

**Comment by tfrank64** [comment]
@iainhouston I'm confused by this issue. First, I don't see a section called `Configuring a Notification Service`. Secondly, the link you posted here works fine for me and so does [another link](https://console.ng.bluemix.net/docs/services/mobilepush/t_push_provider_ios.html) in our Readme which points to Bluemix documentation. Are you still experiencing an issue?

**Comment by iainhouston** [comment]
@tfrank64 all working perfectly now thanks. But it wasn't yesterday ... honest!
