### ISSUE TITLE
Can't generate XCode Project for BluePic-Server

### ISSUE THREAD

**Issue by csantanapr** [IBM-Swift/BluePic#287]
BluePic-Server/Makefile is loading the submodule from head instead of the pinned hash 

```
git submodule init
git submodule update --remote --merge
```

Running `make generateXcode`
```
swift package generate-xcodeproj
error: unable to invoke subcommand: /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-05-03-a.xctoolchain/usr/bin/swift-package (No such file or directory)
make: *** [generateXcode] Error 2
```

The Makefile should load the submodule that is pinned (Kitura-Build @ f7b5be7) and not latest (Kitura-Build  @ b676611) from head from remote repo, it should be change to. This creates a great pain as you have a moving target always using the Kitura-Build from head and not a reliable version that BluePic can count on.
```
git submodule update --init
```
Latest Kitura-Build support 06-06 and BluePic only 05-03

To workaround need to do 2 things:
1 Change to old syntax to generate XCode in Kitrua-Build/build/Makefile
   ```
    generateXcode: build
	swift build --generate-xcodeproj
   ```

2 Run make again to generate XCode project
   ` make generateXcode`

3 XCode will have errors then run
   ` make fixXCode`

Open XCode 7 with ToolChain with 05-03, clean, build and run

This was the only way to get the server running on XCode.

The other problem is that you can't have two XCode windows open with different ToolChains one for BluePic-iOS to default ToolChain and another for BluePic-Server with ToolChain 05-03 this doesn't provide a good experience to run and debug both the iOS App and the Server at the same time.

**Comment by rolivieri** [comment]
@csantanapr - Can you schedule a 30 min meeting for tomorrow Thursday in the afternoon? We can discuss the issues you are having.

**Comment by csantanapr** [comment]
invite sent.

**Comment by rolivieri** [comment]
@csantanapr Thanks for going over the issue with the makefile! We just tested and pushed the change/fix.
