### ISSUE TITLE
Could not find service BluePic-Insights-for-Weather to bind to .....

### ISSUE THREAD

**Issue by kweinmeister** [IBM-Swift/BluePic#292]
@chuckbrant commented on [Sun Jul 10 2016](https://github.com/IBM-Swift/Kitura/issues/595)

Using the "easy button" within the readme, the deployment fails with "Could not find service BluePic-Insights-for-Weather to bind to ....."

---

@kweinmeister commented on [Mon Jul 11 2016](https://github.com/IBM-Swift/Kitura/issues/595#issuecomment-231738138)

Moving this issue to the [BluePic repo](https://github.com/IBM-Swift/BluePic)

**Comment by rolivieri** [comment]
@chuckbrant - We just used the deploy to bluemix button and it worked just fine. We had an issue with one of the services but that got fixed last week. Can you try again? 
<img width="851" alt="screen shot 2016-07-11 at 10 51 45 am" src="https://cloud.githubusercontent.com/assets/6609246/16737638/df650516-4757-11e6-857d-baf789aa9cff.png">

**Comment by rolivieri** [comment]
This issue can no longer be reproduced; hence, closing it. If you are still having problems, please let us know.

**Comment by chuckbrant** [comment]
Thanks, I was able to deploy
