### ISSUE TITLE
Setup CI using Travis CI.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/BluePic#298]
- CI for iOS component.
- CI for Kitura-based server component.

**Comment by rfdickerson** [comment]
We could do this, if you'd like.

**Comment by rolivieri** [comment]
@rfdickerson I just learned you are working on this. If you are going to work on this, make sure you use Package-Builder for the server side. We can transfer it to Brian otherwise. Thanks!

**Comment by rfdickerson** [comment]
I don't have time to do much more than what I already did, I'm afraid. Will PackageBuilder be able to kick off a build of both BluePic-iOS and also BluePic-Server? @BDHernand thoughts?

**Comment by rolivieri** [comment]
@rfdickerson Ok, no problem. Brian will take what you did and build on top of it to ensure we integrate with Package-Builder. To answer your question, Package-Builder won't probably handle the iOS side, just the Server side. We would need a "hybrid" solution.

@BDHernand - I am also adding you as an assignee so you can take over once Robert completes his changes.

**Comment by rfdickerson** [comment]
My changes have been merged in- so handing it off to Brian.

**Comment by BDHernand** [comment]
issued PR on this
