### ISSUE TITLE
Push notifications not working in Xcode 8 beta.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/BluePic#299]
After debugging the issue, this may be an issue in the Push SDK. We are currently looking into it.

**Comment by tfrank64** [comment]
Communications are in progress with BMS push team. Yesterday, APNS may have had issues yesterday, but today we are still having issues.

**Comment by rolivieri** [comment]
We engaged the MobileFirst support team and we have confirmed that even their sample push application does not work with Xcode 8.

They are currently working on adding support for Xcode 8. 

We have another meeting set up with them in about two weeks to follow up.

**Comment by tfrank64** [comment]
It seems the push SDK has been updated, I will test it out soon. https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-swift-push

**Comment by tfrank64** [comment]
I integrated the new sdk and it didn't work, but I eventually found out I needed to enable push in the capabilities tab and now BluePic and receive push notifications again.
![image](https://cloud.githubusercontent.com/assets/4023136/18402629/f72bc900-76a5-11e6-8227-ff6b1dbf8fc4.png)

The bad news, we get a 404 message when trying to send push notifications through open whisk.

**Comment by tfrank64** [comment]
push notifications seem to be working great.
