### ISSUE TITLE
BluePic incompatible with Bluemix Swift Buildpack

### ISSUE THREAD

**Issue by kholdaway** [IBM-Swift/BluePic#302]
The Bluemix swift build pack on supports up to swift-DEVELOPMENT-SNAPSHOT-2016-06-06-a. See https://github.com/IBM-Swift/swift-buildpack.

However this sample requires DEVELOPMENT-SNAPSHOT-2016-06-20-a. See https://github.com/IBM-Swift/BluePic/blob/master/BluePic-Server/.swift-version#L1

Is there a way to run this on Bluemix?

When I follow the instructions here I get these errors
2016-08-09T10:32:17.23-0400 [STG/0] OUT -----> Installing Swift DEVELOPMENT-SNAPSHOT-2016-06-20-a
2016-08-09T10:32:17.32-0400 [STG/0] ERR DEPENDENCY_MISSING_IN_MANIFEST: 'swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a.tar.gz'
2016-08-09T10:32:17.33-0400 [STG/0] OUT Staging failed: Buildpack compilation step failed
2016-08-09T10:32:17.50-0400 [API/1] ERR encountered error: App staging failed in the buildpack compile phase

**Comment by kurtismgit** [comment]
@kholdaway This might be resolved now.  I followed the manual steps (not the IBM Cloud Tools for Swift) and I was able to deploy the BluePic Kitura server to BlueMix.  The manifest file:
https://github.com/IBM-Swift/BluePic/blob/master/manifest.yml

Has this line:
buildpack: https://github.com/IBM-Swift/swift-buildpack.git#develop

And the develop branch of swift-buildpack supports DEVELOPMENT-SNAPSHOT-2016-06-20-a

**Comment by tfrank64** [comment]
Yes, this should not be an issue if you setup through the manual route. Additionally, I think the ICT app has been updated to fix this issue as well, if you choose to use that route. Are you still having issues @kholdaway ?

**Comment by tfrank64** [comment]
The originally issue is resolved, I will close this issue now.
