### ISSUE TITLE
Readme steps for Facebook and Redeploy BluePic app to Bluemix

### ISSUE THREAD

**Issue by kurtismgit** [IBM-Swift/BluePic#305]
The steps for creating a Facebook app are incomplete.  After you hit create the app, there are missing steps about setting the BundleID and enabling SSO.  I eventually found this doc:
https://developers.facebook.com/docs/ios/getting-started

The 'Configure Facebook App Settings for iOS' section of that doc explains steps that are missing from the BluePic readme file.

Also, in the readme step 4 it talks about 'CFBundleURLType'.  I never saw that, instead I see 'URL types' so talking about 'CFBundleURLType' was totally confusing.  I believe this is because some developer checked in the Info.plist file that alreay has a CFBundleURLType.  So this field isn't empty to start with, instead it set to fb1545401759089721 and renders as 'URL types' from the beginning.  See:
https://github.com/IBM-Swift/BluePic/blob/master/BluePic-iOS/BluePic/Configuration/Info.plist

Finally, '5. Redeploy BluePic app to Bluemix' the second option for using the CF CLI to `cf push` from your local copy of the repo.  Before you do `cf push` you need to modify the manifest.yml file and set the application name to the name of the application that's already deployed to Bluemix.  Without this `cf push` will create a new version of the app and not update the existing app.

**Comment by tfrank64** [comment]
@kurtismgit To your first point, we have instructions about setting the Bundle ID for your Facebook app, step 5 in that Facebook Readme section. Not sure what you mean by SSO in the context of BluePic.

Secondly, good find with the info.plist stuff since it is already pre-populated. I adjusted the Readme accordingly on our develop branch.

About the "5. Redeploy BluePic app to Bluemix" instructions, I'm not sure what needs to change because we never require the developer to change the manifest's app name. So it should just update the same app they originally deployed.

**Comment by kurtismgit** [comment]
@tfrank64 Your absolutely regarding the Facebook setup.  I most have been moving too fast and accidentally hit the 'Skip and Create App' button on the quick start wizard.  My bad.

Regarding updating manifest file.  The problem is because in Step 2 of the 'Manual configuration and deployment' section we are instructed to clone the project via:

git clone https://github.com/IBM-Swift/BluePic.git

Then in step "3. Create BluePic application on Bluemix", we use the button to name the app and do the actual deploy.  That deploy changes the app name that's in the manifest in the jazz hub project it deploys.  However that's not the same manifest file that we got when cloning the project.

Also, by the way the deploy button deploys from 'develop' branch.  But we are told to clone master.  Seems like these 2 need to be in sync.

**Comment by tfrank64** [comment]
@kurtismgit I see what you mean with the deploy to Bluemix button, in the Readme, we now instruct developers to ensure they name their application `BluePic`.

Additionally, I updated the master branch deploy to Bluemix button to deploy the master branch.

**Comment by kurtismgit** [comment]
@tfrank64 the updates look good, but I don't believe you can tell everyone to use `BluePic` as the name.  When you click the Deploy to Bluemix button and enter app name, apparently that page is doing some sort of validation to see if that name is already in use.  If I just enter `BluePic` it tells me the name is already in use.  But I know that I never used it.  I even had a cooworker try this and he never touched `BluePic` and it told him it was in use as well.

I'm not sure the scope of this validation check, but please consider this issue.

**Comment by tfrank64** [comment]
@kurtismgit interesting issue, I now specify that your Bluemix app name just needs to match whatever is in your manifest.yml.

**Comment by kurtismgit** [comment]
Looks good to me.  I feel you've addressed all my readme concerns, hence closing this issue.  Thx!
