### ISSUE TITLE
OpenWhisk weather function fails

### ISSUE THREAD

**Issue by kurtismgit** [IBM-Swift/BluePic#307]
I'm still trying to run the BluePic app and now I'm hitting a problem with the OpenWhisk weather action.  When I try to post an image within the iOS app I can see some of the OpenWhisk actions run.  There seems to be a problem with the weather action.  It's returning { "weather": "" } and this causes processImage to fail with { "error": "the action did not return a valid result" }.

I can see (in wsk activiation poll) that the weather action is getting a 401 unauthorized.  I think there's a compatibility issue between the InsightsForWeather SDK that Weather.swift is using and the current version of the weather service on BlueMix.  I think the BlueMix weather service recently changed from 'Insights for Weather' to 'Weather Company Data for IBM BlueMix' and the weather SDK doesn't seem to work with the new service.

I tried commenting here, but no response yet:
https://github.com/IBM-Swift/swift-watson-sdk/issues/30

**Comment by kurtismgit** [comment]
Be sure to take a look at the comments in [swift-watson-sdk issue](https://github.com/IBM-Swift/swift-watson-sdk/issues/30).  Seems like the understand that SDK is unable to talk the the current Bluemix weather service.  For now, I'll just change my copy of the weather OpenWhisk action to return some hardcoded data.  But want to make sure you're aware of this issue, because it causes /processImage whisk action to fail.

**Comment by tfrank64** [comment]
@kurtismgit Thanks for this, we are aware of the issue and we are working on a plan to avoid this issue in the future. Unfortunately, it is not completely in our control.

**Comment by rolivieri** [comment]
To address this issue, a few different pieces need to be fixed. We have reached out to the corresponding teams. It may be a few weeks before this gets sorted out though.

**Comment by kurtismgit** [comment]
What do you guys think about the /processImage flow being able to complete even when weather action fails?  Essentially changing BluePic so that everything still works, except you wouldn't have any weather data.

**Comment by kholdaway** [comment]
Any updates on this?

**Comment by rolivieri** [comment]
BluePic is very resource constrained at the moment… we are in touch with the teams BluePic has external dependencies on. We expect to have fixes for these issues in the next following weeks. In the meantime, yes, there is an issue with the weather service (and related SDK) that impacts the OpenWhisk sequence execution. However, this does not affect the main functionality of the app (e.g. uploading pics, seeing the feed, MCA authentication, etc.).

**Comment by rolivieri** [comment]
Quick update. This item is currently being addressed as part of issue #286.

**Comment by rolivieri** [comment]
Fix is now in develop branch. Closing issue. We will merge into master early next week.
