### ISSUE TITLE
Does "Deploy" on IBM Cloud Tools for Swift Populate Database?

### ISSUE THREAD

**Issue by tengpeng** [IBM-Swift/BluePic#308]
I find if I simply click deploy or deploy on IBM Cloud Tools for Swift, it won't upload new database to the cloud. But if I use .sh manually, it would.

**Comment by rolandoasmat** [comment]
Hello, the "Deploy" button only deploys the server code to Bluemix and it will not populate the database. The populate scripts found in BluePic/Cloud-Scripts are executed automatically by IBM Cloud Tools only once a new BluePic Project option is selected and completed when creating a new Project. 
Also, feel free to post any further questions here that may be related:
https://developer.ibm.com/answers/topics/cloud-tools-for-swift/

**Comment by tfrank64** [comment]
@tengpeng Did you have any more concerns with this issue?

**Comment by tengpeng** [comment]
No. Your answer is perfect. Please close this issue.
