### ISSUE TITLE
Add unit tests to BluePic-Server

### ISSUE THREAD

**Issue by king33** [IBM-Swift/BluePic#315]

**Comment by rfdickerson** [comment]
More importantly- integration tests. Take a look at the test cases that use `URLSession` and spin up a Kitura server during testing time:

https://github.com/IBM-Swift/Blitter/blob/master/Tests/BlitterTests/BlitterTests.swift

**Comment by kweinmeister** [comment]
Another option: https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml

**Comment by rfdickerson** [comment]
Yeah, that's the other option. I think checking in the `cloud_config.json` file will end up being less work since Swift-cfenv is set up to read in those json files and interpret the VCAP params. Otherwise, we'd have to do a lot of this stuff ourselves if the env vars are defined there.

**Comment by tfrank64** [comment]
Our populator script with run before each test now, reseting the database.

**Comment by tfrank64** [comment]
In regards to the last comment, I have commented out the reset call to speed up development.

Additionally, testing status is that the unprotected endpoints are mostly tested.

**Comment by tfrank64** [comment]
Refer to https://github.com/IBM-Swift/BluePic/blob/develop/BluePic-Server/Sources/BluePicApp/ServerController.swift#L113 to perform authenticated requests. Ensure MCA guid is correct.

**Comment by tfrank64** [comment]
BluePic-Server tests are done and working for Mac. Need to test on Linux more.

**Comment by tfrank64** [comment]
So far, the problem on Linux seems to be that intermittently, the authorization header in my request comes out as nil on the server side. Seems like it could be a Swift issue, but I'm unsure.

**Comment by tfrank64** [comment]
Linux tests are now working using Kitura-net, may need to file issue for why they aren't working with URLSession.
