### ISSUE TITLE
Review need for using libdispatch to achieve async functionality

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/BluePic#316]
I believe Kitura-net now has async behavior; if so, we could then remove some of the code we introduced to achieve async functionality. For instance, see RouterUtils: 
`DispatchQueue.global().async...`

**Comment by shmuelk** [comment]
KituraNet.request (i.e. ClientRequest) does NOT have asynchronous capability.

As we are planning on deprecating that API. We don't plan on adding asynchronous capabilities.

**Comment by rfdickerson** [comment]
I recommend creating a `DispatchQueue` in that controller and using its `async` method for doing that operation.

**Comment by shmuelk** [comment]
Dave Grove recommended against creating extra Concurrent DispatchQueue's and instead use the Global one as this code was already doing. There are only so many threads on mac's in particular.

**Comment by rfdickerson** [comment]
Does it matter how many DispatchQueues there are at the system level? I think @davidungar and my code is pretty liberal with creating new queues if appropriate. Would love more insight in this issue, @dgrove-oss .

**Comment by dgrove-oss** [comment]
At the system level, the only scheduable queues (queues that actually get worker threads that can dequeue and execute workitems) are the 6 "built-in" global queues.  All the additional user-created concurrent queues end up targeting one of the built-in queues to get their workitems executed.  When workitems are enqueued on an empty user-created queue, libdispatch enqueues a workitem on the appropriate global queue to drain that user queue.  So if you have multiple user queues with the same QoS target (thus targeting the same global queue), you can see batching effects.  For example, I create q1 and q2 both targeting the same global queue.  I then alternately enqueue workitems on each.   You are very likely to see the workitems being serviced by the worker threads in "clumps": a clump of items from q1, then a clump from q2, and so on.   

Therefore, if all you need is the core API of a concurrent queue (you are only going to use async; not sync or barriers), then I would recommend just using one of the six global concurrent queues.  This avoids introducing the additional level of scheduling overhead and batching that you probably didn't actually want.  It is also a faster path through the dispatch code, but that probably matters less than the extra-level of scheduling as the underlying worker threads attempt to drain each user-level queue in succession.

However, if you need the full semantics of having your own logically distinct concurrent queues (barrier blocks, sync, etc), then you should create them and not be too concerned about the overheads.   The advice to use the global queues directly was motivated by trying to get the most efficient and scalable scheduling of workitems possible for Kitura (which was not using more than just async).

**Comment by rolivieri** [comment]
Great info & details, thanks all!

**Comment by rfdickerson** [comment]
This is amazing, @dgrove-oss! Very rich area to explore here. I would love more documentation on these internals with various benchmarks, etc. to help application developers understand which to use.

**Comment by davidungar** [comment]
Thank you, Dave, and very clear, too.

This is a great example of the subjectivity of abstractions.

- David

**Comment by rfdickerson** [comment]
haha, or "abstractions are more real than you think" ;)

**Comment by davidungar** [comment]
What is reality?
