### ISSUE TITLE
Building iOS app on device now requires a development team.

### ISSUE THREAD

**Issue by tfrank64** [IBM-Swift/BluePic#323]
Previously, a user could get the BluePic-iOS Xcode project, set the team to none, and run on their device. In Xcode 8, it appears a development team needs to be set. To adjust for this, we need to:

- Verify the app will work once a team is set and a provisioning profile is made.
- Update Readme accordingly to inform users this needs to be done for running on a device.

The error:
![image](https://cloud.githubusercontent.com/assets/4023136/18887618/6b9512c0-84ba-11e6-9756-c2485b901e7b.png)

**Comment by tfrank64** [comment]
My findings have told me that yes, you do need an Apple developer account to build on a device.
Previously, a user could build BluePic with just an Apple ID, but now that we have had to enable push notifications within Xcode, our app specifically looks for a provisioning profile with push enabled. So it seems users need a push enabled profile to use now to run on a device.

Additionally, I did a test with code before we enabled push in Xcode and I was able to build for a device in Xcode 7 with no team set. I then moved to Xcode 8 with no team set, and I get compile errors like `Code signing is required for product type 'Application' in SDK 'iOS 10.0'`. I can't really explain this, but **what fixed the issue was setting the team and setting the provisioning profile matching the BluePic bundle ID.**

**Comment by tfrank64** [comment]
After testing with my other Apple dev account, what a developer needs to do to run BluePic on a physical device is either:
1. Disable the push notification capability in Xcode and just use a wildcard provisioning profile associated with their team. In this case, push will not work.
2. Change the BluePic bundle ID to something unique, create an App ID with push enabled, and create a provisioning profile matching that ID. Using that profile in Xcode should allow you to build to a device and receive push notifications.

**Comment by rfdickerson** [comment]
Oh ok, this is very related to my problem with enabling a build on Travis CI. Also, when I open the project, I see:

<img width="529" alt="screen shot 2016-09-30 at 5 35 05 am" src="https://cloud.githubusercontent.com/assets/1310293/18989181/17aca8d6-86d0-11e6-9aaf-3c2989c5dd44.png">

**Comment by tfrank64** [comment]
@rfdickerson Are you able to get around that by setting a different profile? Ideally, I would like to use the automatic signing management, but it would not work at all yesterday.

**Comment by rfdickerson** [comment]
My IBM Provisioning profile (under automatic signing management) does not work at all. It doesn't like that bundle id. However, switching to my personal account profile (Robert F. Dickerson, yeah I pay $99 a year for it) will allow me to build.

**Comment by tfrank64** [comment]
Mine used to work under IBM, but now I can't seem to download profiles properly. I get this error `No profiles for 'com.ibm.test1' were found` when I know it exists.

**Comment by tfrank64** [comment]
After more research, manual management of code signing is recommended according to IBM [instructions](https://w3-connections.ibm.com/wikis/home?lang=en-us#!/wiki/Wa23469728339_4c0c_bbaa_bd2061524280/page/Getting%20Started%20As%20An%20Apple%20Developer%20in%20IBM). Given that, we decided to disable push by default in Xcode so that a dev could get up and running more quickly.

I have added instructions to the README and another wiki page for what a dev should do to run BluePic on a device.

**Comment by rolivieri** [comment]
@tfrank64 Just reviewed the new contents and made some minor edits. Thanks for putting this info into writing!
