### ISSUE TITLE
Update to Swift 3.0.1 and Kitura 1.1

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/BluePic#364]

**Comment by tfrank64** [comment]
Started looking into this, currently waiting for Anton to update the appropriate SDKs.

**Comment by tfrank64** [comment]
Need to remove explicit reference of BlueCryptor in Package.swift once that package is updated to use the COpenSSL version I need (2.2). I informed Bill of this need.

**Comment by rfdickerson** [comment]
Hate to bring this up- but you should go ahead and update to Kitura 1.2 since on Kitura 1.1 the debugging on XCode is broken.
