### ISSUE TITLE
Facebook login failure

### ISSUE THREAD

**Issue by scauos** [IBM-Swift/BluePic#367]
When I sign in with Facebook, it simply get this failure below.

Get User By ID Error: The operation couldn’t be completed. (BMSCore.BMSCoreError error 2.)
Check If User Already Exists Error: Connection Failure
Login Error: Connection Failure

What is that? My connection is well but...

**Comment by tfrank64** [comment]
I confirmed, Facebook login is still working for me. Have you gone through the steps mentioned here: https://github.com/IBM-Swift/BluePic#optional-features-to-configure to setup Facebook and MCA?

**Comment by scauos** [comment]
Yes, I did. But still failed

**Comment by tfrank64** [comment]
I just did a fresh clone of BluePic and it still works for me.
Is there any more information you can give me?

- What iOS version are you using?
- Is this on a simulator?
- Did you run `pod install`? Because it is not necessary.
- Are you able to get images on the main feed?
- Are you able to post any images or does the login screen just pop up?

You could try resetting your database to start fresh. I'll keep looking into this.

**Comment by dazhendong** [comment]
I am sure I didn't run ``pod install`` and I am not able to get images on the main feed even post any images.
And one more question. I began learn iOS programming 3 months ago. And the architecture of this app is MVVM, right? I am not familiar with this architecture.

**Comment by tfrank64** [comment]
@dazhendong Are you having the same issues as scauos?

Have you tried creating the BluePic app/runtime through [IBM Cloud Tools for Swift](http://cloudtools.bluemix.net/)? I am testing this now, will get back to you with my results on Monday.

Yes, we are using MVVM. Not quite as simple as MVC, but definitely has its benefits.

**Comment by scauos** [comment]
I have solved this problem. And I try to learn this design pattern MVVM through your creative app. But still configured . Do you have some link teaching MVVM I can learn from. Thanks.

**Comment by tfrank64** [comment]
Thats great. I also got things working fine by using the IBM Cloud Tools for Swift app and then configuring Facebook and MCA.

One good resource is this: https://www.raywenderlich.com/74106/mvvm-tutorial-with-reactivecocoa-part-1
Also, haven't completely read this one, but Artsy is usually good: http://artsy.github.io/blog/2015/09/24/mvvm-in-swift/
