### ISSUE TITLE
Insights for Weather service is now deprecated.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/BluePic#375]
See following URL for more details: https://console.ng.bluemix.net/docs/services/InsightsWeather/index.html

"The revised service is available in Bluemix as Weather Company Data for IBM Bluemix."

**Comment by tfrank64** [comment]
It looks like our weather insights service was migrated already to Weather Company Data. We could just change our service name and ensure that it still works, once OpenWhisk is working again. Depends on #379

**Comment by tfrank64** [comment]
To confirm, the insights weather service was migrated to be Weather Company Data service. Here is BluePic's service and newly created weather service for reference:
```
BluePic-Insights-for-Weather       weatherinsights          Free-v2             BluePic                      create succeeded
Weather Company Data-tempp         weatherinsights          Free-v2                                          create succeeded
```


 The API did change, but Vince already updated the [swift-watson-sdk awhile back](https://github.com/IBM-Swift/swift-watson-sdk/commit/0661e9b2fe586844d3019e27afb2afcb17102d36)
Additionally, [OpenWhisk](https://github.com/openwhisk/openwhisk/blob/master/core/swift3Action/spm-build/Package.swift) is currently using version `0.4.1` of that SDK so it includes the weather api updates.
In the end, no further action needs to be taken.
