### ISSUE TITLE
Replace Alchemy with equivalent service

### ISSUE THREAD

**Issue by tfrank64** [IBM-Swift/BluePic#384]
AlchemyAPI is being deprecated on Bluemix, we will need to updated to a similar service, if possible, for image analysis.

Announcement: https://www.ibm.com/blogs/bluemix/2017/03/bye-bye-alchemyapi/

**Comment by trulymobilenwp** [comment]
Needs to be https://www.ibm.com/watson/developercloud/visual-recognition.html

**Comment by tfrank64** [comment]
This is close to being done, doing end to end tests now using Visual Recognition in OpenWhisk

**Comment by tfrank64** [comment]
PR with this change is open https://github.com/IBM-Swift/BluePic/pull/391

**Comment by tfrank64** [comment]
PR merged
