### ISSUE TITLE
Using Method #1 - is not working. this is after the recent refactoring.

### ISSUE THREAD

**Issue by ljbennett62** [IBM-Swift/BluePic#401]
The app attempts to start and I get the following:

![image](https://cloud.githubusercontent.com/assets/17774650/24914300/b3d8f610-1e88-11e7-91b6-f655ed02db67.png)

I initially thought it might be a memory/space problem - but I removed all apps and services in Bluemix and started fresh deployment. The app just recycles to start and stop.

**Comment by tfrank64** [comment]
So your app will not deploy to Bluemix? You are using IBM Cloud Tools for Swift?
I was able to deploy yesterday using multiple methods, but I can try again.

**Comment by ljbennett62** [comment]
@tfrank64 - so it deploys if I use the "deploy to bluemix" button - it is not deploying using the IBM Cloud Tools for Swift methodology.  can you screen hero with me today and we can go through it?

**Comment by ljbennett62** [comment]
Starting working - so will close issue

**Comment by ljbennett62** [comment]
started working - so closing issue
